# Generated by Django 3.1.2 on 2020-11-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=1, upload_to='profile', verbose_name='الصوره الشخصيه :'),
            preserve_default=False,
        ),
    ]
