# Generated by Django 3.1.2 on 2020-11-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=1, max_length=50, verbose_name='المحافظه :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='address_detail',
            field=models.CharField(default=1, max_length=150, verbose_name='العنوان بالتفصيل :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='دكتور ؟'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=1, max_length=50, verbose_name='الهاتف :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='specialist_doctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='متخصص في :'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(default=1, max_length=50, verbose_name='نبذه عنك :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='wating_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مده الانتظار :'),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(default=1, max_length=50, verbose_name='عدد ساعات العمل :'),
            preserve_default=False,
        ),
    ]
