# Generated by Django 3.1.2 on 2020-11-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_join_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_preson',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=50, verbose_name='النوع :'),
            preserve_default=False,
        ),
    ]
