# Generated by Django 3.1.2 on 2020-11-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201105_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default=1, max_length=50, verbose_name='اللقب :'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, choices=[('جراحه اورام', 'جراحه اورام'), ('نفسي', 'نفسي'), ('مخ واعصاب', 'مخ واعصاب'), ('جراحه اطفال', 'جراحه اطفال'), ('انف واذن وحنجره', 'انف واذن وحنجره'), ('جلديه', 'جلديه'), ('اطفال حديثي الولاده', 'اطفال حديثي الولاده'), ('جراحه اوعيه دمويه', 'جراحه اوعيه دمويه'), ('قلب واعويه دمويه', 'قلب واعويه دمويه'), ('جراحه تجميل', 'جراحه تجميل'), ('امراض دم', 'امراض دم'), ('اورام', 'اورام'), ('تخسيس وتغذيه', 'تخسيس وتغذيه'), ('جراحه سمنه مناطير', 'جراحه سمنه مناطير'), ('عظام', 'عظام'), ('نساء وتوليد', 'نساء وتوليد'), ('اسنان', 'اسنان'), ('باطنه', 'باطنه')], max_length=50, null=True, verbose_name='دكتور ؟'),
        ),
    ]
